# -*- coding: utf-8 -*-
"""K-Nearest Neighbors Menggunakan Python (201855202065).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vVTMzEAIANHwawGD9S3sW2rsXw1_zk_H
"""

#Import Libaries
import pandas as pd 
import matplotlib.pyplot as plt

dataset = pd.read_csv('iris.csv')

#menampilkan dataset 5 teratas
dataset.head(5)

#menampilkan row masing-masing spesies
dataset.groupby('species').size()

#Membuat Data Frame Pada Masing-Masing Spesies
setosa = dataset[dataset['species']=='setosa']
versicolor = dataset[dataset['species']=='versicolor']
virginica = dataset[dataset['species']=='virginica']

setosa.describe()

virginica.describe()

# deskripsi dataset secara kesuluruhan
dataset.describe()

#Membuat Grafik Perbandingan Sepal dan Petal
plt.figure()
fig,ax=plt.subplots(1,2,figsize=(15, 5))
setosa.plot(x="sepal_length", y="sepal_width", kind="scatter",ax=ax[0],label='setosa',color='r')
versicolor.plot(x="sepal_length",y="sepal_width",kind="scatter",ax=ax[0],label='versicolor',color='b')
virginica.plot(x="sepal_length", y="sepal_width", kind="scatter", ax=ax[0], label='virginica', color='g')

setosa.plot(x="petal_length", y="petal_width", kind="scatter",ax=ax[1],label='setosa',color='r')
versicolor.plot(x="petal_length",y="petal_width",kind="scatter",ax=ax[1],label='versicolor',color='b')
virginica.plot(x="petal_length", y="petal_width", kind="scatter", ax=ax[1], label='virginica', color='g')

ax[0].set(title='Perbandingan Sepal', ylabel='Lebar sepal (cm)')
ax[1].set(title='Perbandingan Petal',  ylabel='Lebar petal(cm)')
ax[0].legend()
ax[1].legend()
plt.savefig('asda.png')